version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:37"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - documentation
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:47"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: ci
